
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from 'react'
import Loading from '@/app/loading'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props:{
  children: React.ReactNode,
  // analytics: React.ReactNode,
  // team:React.ReactNode,
  // modal:React.ReactNode
}) {


  return (
    <html lang="zh-cn">
      <body className={inter.className}>

        <Suspense fallback={<Loading/>}>
        app根页面layout.tsx参数<br/>
        {props.children}
        {/* {props.analytics} */}
        {/* {props.team} */}
        {/* {props.modal} */}

        <br/>

        </Suspense>
  
        </body>
    </html>
  );
}
